FROM python:3.6-alpine

RUN adduser -D microblog

WORKDIR /home/microblog

COPY requirements.txt requirements.txt
COPY requirements /home/microblog/requirements

RUN python -m venv venv
RUN apk --update add --virtual build-dependencies libffi-dev openssl-dev python-dev py-pip build-base \
  && venv/bin/pip install --upgrade pip \
  && venv/bin/pip install -r requirements/test.txt \
  && apk del build-dependencies
RUN venv/bin/pip install gunicorn
RUN venv/bin/pip install pymysql

COPY app app
COPY migrations migrations
COPY test.sh test.sh
COPY pytest.ini pytest.ini
COPY tests tests
RUN chmod +x test.sh

ENTRYPOINT ["./test.sh"]